import type { RouteConfig } from './schema.ts';

export const routes: RouteConfig[] = [
  {
    id: 'home',
    path: '/',
    title: 'Zero Company Field Guide — Classes, Operators & Squad Decisions',
    description: 'Choose a verified STAR WARS Zero Company guide for classes, operators, difficulty, permadeath, and squad planning.',
    kind: 'content',
    releaseState: 'LOCAL_ONLY',
    published: false,
    sitemap: false,
  },
  {
    id: 'classes',
    path: '/classes/',
    title: 'Zero Company Classes & Specializations — Verified Guide',
    description: 'Compare officially documented Zero Company classes, battlefield roles, and currently verified specialization details.',
    kind: 'content',
    releaseState: 'LOCAL_ONLY',
    published: false,
    sitemap: false,
  },
  {
    id: 'operators',
    path: '/operators/',
    title: 'Zero Company Operators & Characters — Verified Guide',
    description: 'Review officially documented Zero Company operators, character roles, and the current evidence boundary.',
    kind: 'content',
    releaseState: 'LOCAL_ONLY',
    published: false,
    sitemap: false,
  },
  {
    id: 'difficulty-permadeath',
    path: '/guides/difficulty-permadeath/',
    title: 'Zero Company Difficulty & Permadeath — Official Answers',
    description: 'Understand officially documented difficulty and permadeath choices without unsupported gameplay claims.',
    kind: 'content',
    releaseState: 'LOCAL_ONLY',
    published: false,
    sitemap: false,
  },
  {
    id: 'squad-size-operators',
    path: '/guides/squad-size-operators/',
    title: 'Zero Company Squad Size & Operators — Verified Guide',
    description: 'Understand officially documented squad composition, operator selection, and current unknowns.',
    kind: 'content',
    releaseState: 'LOCAL_ONLY',
    published: false,
    sitemap: false,
  },
  {
    id: 'privacy',
    path: '/privacy/',
    title: 'Privacy — Zero Company Field Guide',
    description: 'Privacy information for the local Zero Company Field Guide build.',
    kind: 'legal',
    releaseState: 'LOCAL_ONLY',
    published: false,
    sitemap: false,
  },
  {
    id: 'terms',
    path: '/terms/',
    title: 'Terms — Zero Company Field Guide',
    description: 'Terms and independent-site information for Zero Company Field Guide.',
    kind: 'legal',
    releaseState: 'LOCAL_ONLY',
    published: false,
    sitemap: false,
  },
  {
    id: 'not-found',
    path: '/404.html',
    title: 'Page not found — Zero Company Field Guide',
    description: 'The requested local guide route was not found.',
    kind: 'error',
    releaseState: 'LOCAL_ONLY',
    published: false,
    sitemap: false,
  },
];

export function getRoute(id: RouteConfig['id']) {
  return routes.find((route) => route.id === id);
}
