import type { SourceRecord } from './schema.ts';

export const sources: SourceRecord[] = [
  {
    id: 'source:official-game-page',
    label: 'Electronic Arts — official Zero Company game page',
    url: 'https://www.ea.com/games/starwars/zero-company',
    evidenceClass: 'OFFICIAL',
    gameVersion: 'Launch page, 2026-08-27',
    lastVerified: '2026-08-27',
    publicAllowed: true,
    editorialJudgment: false,
  },
  {
    id: 'source:official-q-and-a',
    label: 'Electronic Arts — Answering the Internet’s Biggest Questions about SWZC',
    url: 'https://www.ea.com/games/starwars/zero-company/news/answering-biggest-questions',
    evidenceClass: 'OFFICIAL',
    gameVersion: 'Official pre-launch Q&A, 2026-07-21',
    lastVerified: '2026-08-27',
    publicAllowed: true,
    editorialJudgment: false,
  },
  {
    id: 'source:official-gameplay-deep-dive',
    label: 'Electronic Arts — Lead Zero Company to Victory',
    url: 'https://www.ea.com/games/starwars/zero-company/news/lead-zero-company-to-victory',
    evidenceClass: 'OFFICIAL',
    gameVersion: 'Official pre-launch deep dive; article states details were subject to change',
    lastVerified: '2026-08-27',
    publicAllowed: true,
    editorialJudgment: false,
  },
  {
    id: 'source:ea-help-platforms',
    label: 'EA Help — platforms and PC requirements guide',
    url: 'https://help.ea.com/en/articles/star-wars/zero-company/platforms-pc-requirements-guide/',
    evidenceClass: 'OFFICIAL',
    gameVersion: 'Launch support guide, 2026-08-27',
    lastVerified: '2026-08-27',
    publicAllowed: true,
    editorialJudgment: false,
  },
  {
    id: 'source:ea-launch-release',
    label: 'Electronic Arts — August 27 launch press release',
    url: 'https://news.ea.com/press-releases/press-releases-details/2026/Command-the-Clone-Wars-Most-Cunning-Operatives-in-Star-Wars-Zero-Company-Launching-August-27/default.aspx',
    evidenceClass: 'OFFICIAL',
    gameVersion: 'Launch announcement, 2026-08-27',
    lastVerified: '2026-08-27',
    publicAllowed: true,
    editorialJudgment: false,
  },
  {
    id: 'source:official-gameplay-trailer',
    label: 'EA Star Wars — official gameplay trailer',
    url: 'https://www.youtube.com/watch?v=WxLUZ1omFA8',
    evidenceClass: 'OFFICIAL',
    gameVersion: 'Official gameplay trailer',
    lastVerified: '2026-08-27',
    publicAllowed: true,
    editorialJudgment: false,
  },
];
